### ISSUE TITLE
What is the vocabulary size?

### ISSUE THREAD

**Issue by ShaneeyS** [ChiYeungLaw/LexLIP-ICCV23#1]
Could u please tell me what is the vocabulary size of |V|? I have not found this in paper.

**Comment by ShaneeyS** [comment]
BTW, could you please tell me where is the vocabulary from? Is it from any pretrained corpus, or from some open resources?

**Comment by ChiYeungLaw** [comment]
We use the same vocabulary as the language encoder (bert-base-uncased).

**Comment by ShaneeyS** [comment]
How many hours in total it takes to train this model? (in default settings, for example, 8 V100)

**Comment by ChiYeungLaw** [comment]
around 90h for 14M image-text pairs, 8V100
