### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by yuanze1024** [ChiYeungLaw/LexLIP-ICCV23#4]
Hi, I found this work interesting, but there are several questions:
1. Have you done a fair comparison of the performance gap between your proposed method and BLIP or BLIP2? I only saw CLIP's test results under the "large-scale"test set.
The table below shows the benchmark in BLIP2:
<img width="1163" alt="image" src="https://github.com/ChiYeungLaw/LexLIP-ICCV23/assets/50018861/c369116b-afe0-46d5-8d4f-c46f7d674906">

2. What's more,  I have another question about your "large-scale" setting. 
> In text-to-image retrieval, models retrieve images from the 1k images of Flickr30k and an additional 1M images,  given 4k captions as queries from Flickr30k.

In this case, the GT of a query is just an image in flickr, and there may (or must) be images in the CC dataset that can be well described by the query. In this case, can the Recall really reflect the model?

Please let me know if I misunderstand your work.

**Comment by ChiYeungLaw** [comment]
The primary objective of our large-scale retrieval experiments is to demonstrate the efficacy of the sparse retrieval paradigm (LexLIP) by showcasing its ability to achieve performance on par with the dense retrieval paradigm (CLIP). The focus of our comparison lies not only in showcasing comparable recall scores but, more crucially, in highlighting the **superior speed and reduced index size** offered by the sparse retrieval paradigm.

It is noteworthy that a fair comparison must avoid pitting dual-encoder models (such as LexLIP and CLIP) against the BLIP-family, which incorporates a fusion encoder reranking alongside dual-encoder architecture. The BLIP models, characterized by heightened interaction between images and texts with a fusion encoder, naturally exhibit superior retrieval performance. Therefore, drawing a direct performance comparison between these distinct directions would be inherently unfair.

Furthermore, our arxiv [paper](https://arxiv.org/abs/2302.02908) is contemporaneous with BLIP-2 [paper](https://arxiv.org/abs/2301.12597).
